### ISSUE TITLE
Functional syntax?

### ISSUE THREAD

**Issue by zaydek** [evanw/skew#29]
Hi Evan, I was wondering does Skew support functional primitives such as `{ ...object, x: ..., y: ... }`. My use case would be better interopability with React (e.g. `useReducer`). Thanks!

**Comment by evanw** [comment]
It doesn't support this if I understand you correctly. Objects are not extensible in Skew since they are designed to be compiled to efficient machine code. There is `StringMap` that is extensible, and of course you could write your own custom binding API to a JS object if you wanted to. So you could do something like this:

```rb
def underlay<T>(toCopyFrom StringMap<T>, toCopyInto StringMap<T>) StringMap<T> {
  for key in toCopyFrom.keys {
    if !(key in toCopyInto) {
      toCopyInto[key] = toCopyFrom[key]
    }
  }
  return toCopyInto
}

@entry
def example {
  var object = { "x": 1, "y": 2, "z": 3 }
  object = underlay<int>(object, {
    "x": 4,
    "y": 5,
  })
}
```

As you can see, doing JavaScript-specific stuff like this in Skew is likely not going to be as ergonomic as it would be with JavaScript. Skew is more for writing low-level heavily-optimized code that doesn't make extensive use of existing libraries. I would recommend TypeScript if you're writing code that uses JavaScript libraries heavily.

**Comment by zaydek** [comment]
Thanks so much for the speedy reply. I see what you mean.

Since I'm using esbuild already I can easily opt-in to TypeScript on a file-to-file basis, which is amazing, rather than having to refactor entire projects. That being said, I've never loved TypeScript. I'm actually really only using React right now, and prefer using as few libraries as possible. So investing in a language like Skew wouldn't necesarrily be unfeasible, I'd just need to make sure it can do the heavy lifting JS or TS would otherwise be doing.

I'd be interested to hear if you've had success coupling Skew to React. I imagine you use Skew in tandem with canvas at Figma.

**Comment by evanw** [comment]
> I'd be interested to hear if you've had success coupling Skew to React. I imagine you use Skew in tandem with canvas at Figma.

We do use Skew with the WebGL canvas at Figma, but it's mainly for the custom rendering and animation engine where performance is more of a concern. Our React code uses TypeScript instead of Skew since performance isn't as much a concern for the UI. So both languages are active at the same time and they communicate with each other to form the complete app.

**Comment by zaydek** [comment]
Ah got it. Thank you for the replies! Will go ahead and close this.
